### ISSUE TITLE
Define sensible defaults for vulnerability filters, grouping and issue contents in the sample configuration files

### ISSUE THREAD

**Issue by rsenden** [ryancblack/FoDToJIRA#4]

**Comment by drharper** [comment]
1. Default Filter should be Severity=Critical or High and isSuppressed=False
2. Grouping - No change
3. Issue contents. TBD. Will revisit when we have an answer to the deep link issue

**Comment by rsenden** [comment]
Default filters in sample configuration files have been updated

**Comment by rsenden** [comment]
Additional question: should the JIRA issue show vulnerability ID or issue instance ID?
