### ISSUE TITLE
Investigate changes needed to utilize FoD REST API v3

### ISSUE THREAD

**Issue by rsenden** [ryancblack/FoDToJIRA#6]

**Comment by drharper** [comment]
Change to v3 API looks straightforward:

/api/v1/Vulnerability/?releaseid=<ReleaseID> is replaced by /api/v3/releases/{releaseId}/vulnerabilities
/api/v2/Releases/{releaseId}/Vulnerabilities/{vulnId}/Summary is replaced by /api/v3/releases/{releaseId}/vulnerabilities/{vulnId}/summary
/api/v2/Releases/{releaseId}/Vulnerabilities/BulkEdit is replaced by  /api/v3/releases/{releaseId}/vulnerabilities/bulk-edit

See API Explorer for more details

**Comment by rsenden** [comment]
All code updated to use FoD v3 API
