### ISSUE TITLE
Missing features from the spec

### ISSUE THREAD

**Issue by drharper** [ryancblack/FoDToJIRA#7]
Well, I couldn't find them:-)

Selection criteria:
- isSuppressed (MUST)
- Scantype (SHOULD)

JIRA ticket details:
- JIRA priority - Mapped from FoD severity (MUST)
- Ability to specify static custom fields (MUST)

**Comment by rsenden** [comment]
As described by Ryan, selection criteria are now isSuppressed==false and severityString==Critical|High. Users can configure other filters on any FoD vulnerability field returned by the REST API.

I have added JIRA priority, but for now it is hardcoded to 'Highest'. Mapping from FoD severity still needs to be implemented. As described in the sample configuration file, basically any supported JIRA field can be submitted by simply adding the field name and value to the configuration file.

**Comment by rsenden** [comment]
FoD severity is now being mapped to corresponding JIRA priority in configuration file
